name: FhaNOW
favicon: null
layout_spectrum: 0.3609720184467733
typography_spectrum: 0.2019707835279405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5342447177972645
  lightness: 0.41579636721871793
  saturation: 0.781956649851054
  rhythmicContrast: 0.7072278789710253
purpose: []
